config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :create, :new] 
  end

  resources :posts do
    resources :comments, only: [:create]
    resources :likes, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  belongs_to :user
  belongs_to :post
  after_create :update_counter_for_comments

  private

  def update_counter_for_comments
    post.update(comments_counter: post.comments.count)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_create :update_counter_for_likes

  private

  def update_counter_for_likes
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  belongs_to :user
  has_many :comments
  has_many :likes
  after_create :update_post_counter

  def update_post_counter
    user.update(posts_counter: user.posts.count)
  end

  def most_recent_five_comments
    comments.order('created_at DESC').last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { in: 3..25 }
  validates :posts_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  has_many :posts
  has_many :likes
  has_many :comments

  def most_recent_three_posts
    posts.order('created_at DESC').last(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user = User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(text: comment_parameters[:text], user_id: current_user.id, post_id: @post.id)

    respond_to do |format|
      format.html do
        if @comment.save
          redirect_to user_post_path(@post.user.id, @post.id), notice: 'Comment created successfully'
        else
          redirect_to user_post_path(@post.user.id, @post.id), alert: 'An error occured, please try again!'
        end
      end
    end
  end

  private

  def comment_parameters
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like = @post.likes.create(user_id: current_user.id, post_id: @post.id)

    respond_to do |format|
      format.html do
        if @like.save
          redirect_to user_post_path(@post.user.id, @post.id), notice: 'Liked 👍'
        else
          redirect_to user_post_path(@post.user.id, @post.id), alert: 'An error occured, please try again!'
        end
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.most_recent_three_posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    @comments = @post.comments.order(created_at: :desc)
    @likes = @post.likes.all
  end

  def new
    @current = current_user
  end

  def create
    new_post = current_user.posts.build(post_params)

    if new_post.save
      redirect_to user_post_path(new_post.user_id, new_post.id), notice: 'Post was successfully created.'
    else
      render :new, alert: 'Post was not created.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_create.html.erb
<section class="container mt-5 p-2 bio">
  <%= form_with model:[@post, @post.comments.build], method: :post, local: true do |f| %>
    <%= f.label :text, "Your comment", class: "form-label fs-6" %><br>
    <%= f.text_area :text, size:"50x5", class: "form-control", placeholder: "Add comment...", required: true %>
    <br>
    <%= f.submit "Add comment", data: {disable_with: "Adding..."}, class: "btn btn-primary my-3" %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyVisionOfLife</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'users.css' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <% if notice %>
        <p class="alert alert-success text-center msg"><%= notice %></p>
      <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <nav class="navbar navbar-expand-lg navbar-fluid mb-3" style="background-color: #6D5D6E;">
      <h1>Welcome to my Vision of Life</h1>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/likes/_create.html.erb
<section>
  <%= form_with model:[@post, @post.likes.build] do |f|%>
    <%= f.submit "Like" , data: {disable_with: "Like"}, class: "btn btn-lg mb-3 like"%>
  <%end%>
</section>

app/views/posts/index.html.erb
<div class="card" style="width: 30rem;">
  <div class="user-details container fluid d-flex flex-row border-bottom">
    <img src='<%= @user.photo %>' class="card-img-top" id="user-photo" alt="walk">
    <div class="card-body d-flex flex-column">
      <h3 class="card-title"><%= @user.name %></h3>
      <p class="card-text text-end"><small class="text-body-secondary">Number of posts: <%= @user.posts_counter %></small></p>
    </div>
  </div>

  <ul class="list-group list-group-flush" id="all-posts">
    <% @user.posts.each do |p| %>     
      <li class="list-group-item">
        <h5>Post: <strong><%= p.title %></strong></h5>
      </li>
      <li class="list-group-item"><%= p.text.truncate(90) %></li>
      <li class="list-group-item d-flex flex-row" id="lks-posts">
        <%= link_to 'View post', user_post_path(@user, p), class: 'btn btn-view' %>
        <p>Comments: <%= p.comments_counter %></p>
        <p>Likes: <%= p.likes_counter %></p>
      </li>
      <li>
        <% p.most_recent_five_comments.each do |c| %>
          <p><strong><%= c.user.name %></strong>: <%= c.text %></p>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="card-body d-flex flex-row" id="navigate">
    <%= link_to 'Back', users_path(@user), class: 'btn btn-lg btn-danger' %>
  </div>
</div>

app/views/posts/new.html.erb
<h1 class="users_heading"> Create new post</h1>

<section class="fs-4 p-3 container mt-5 p-2">
  <%= form_with model:[@current_user, @current_user.posts.build], method: :post, local: true do |f| %>
    <%= f.label :title, "Title", class: "form-label fs-3" %>
    <%= f.text_field :title, :placeholder => "Title goes here...", required: true, class: "form-control mb-4" %>
    <%= f.label :text, "Write a new post", class: "form-label fs-3" %>
    <%= f.text_area :text, size: "50x15", :placeholder => "Add your post here...", required: true, class: "form-control" %>
    <%= f.submit "Add Post",  class: "btn btn-primary" %>
  <% end %>
</section>

app/views/posts/show.html.erb
<div class="card" style="width: 30rem;">
  <ul class="list-group list-group-flush" id="all-posts"> 
      <li class="list-group-item">
        <h5><strong><%= @post.title %></strong> by <%= @user.name %></h5>
        <div class="d-flex flex-row statistics">            
          <p>Comments: <%= @post.comments_counter %></p>
          <p>Likes: <%= @post.likes_counter %></p>
        </div>
      </li>
      <li class="list-group-item"><%= @post.text %></li>
      <li>
        <p><strong>Comments:</strong></p>
        <% @post.comments.each do |c| %>
          <p><strong><%= c.user.name %></strong>: <%= c.text %></p>
        <% end %>
      </li>
  </ul>
  <div class="card-body d-flex flex-row" id="navigate">
    <%= render partial: "likes/create" %>
    <%= link_to 'Back', users_path(@user), class: 'btn btn-lg btn-danger' %>
  </div>
  
  <%= render partial: 'comments/create' %>
</div>

app/views/users/_users_info.html.erb
<div class="card mb-3 user_thumbnail" style="max-width: 95%;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src=<%= u.photo %> class="img-fluid rounded-start" alt="walking in the sunset">
    </div>
    <div class="col-md-8">
      <div class="card-body d-flex flex-column">
        <h2 class="card-title m-5">
          <%= link_to user_path(u.id) do %>
            <%= u.name %>
          <% end %>
        </h2>
        <p class="card-text text-end"><small class="text-body-secondary">Number of posts: <%= u.posts_counter %></small></p>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<section class="users">
  <% @users.each do |u| %>
    <%= render partial: 'users_info', locals: {u:u} %>
  <% end %>
</section>

app/views/users/show.html.erb
<div class="card" style="width: 30rem;">
  <div class="user-details container fluid d-flex flex-row border-bottom">
    <img src='<%= @user.photo %>' class="card-img-top" id="user-photo" alt="walk">
    <div class="card-body d-flex flex-column">
      <h3 class="card-title"><%= @user.name %></h3>
      <p class="card-text text-end"><small class="text-body-secondary">Number of posts: <%= @user.posts_counter %></small></p>
    </div>
  </div>
  <div class="card-body">
    <h5><strong>Bio</strong>:</h5>
    <p><%= @user.bio %></p>
  </div>

  <ul class="list-group list-group-flush">
    <% i=1 %>
    <% @user.most_recent_three_posts.each do |p| %>     
      <li class="list-group-item">
        <h5>Post <%= i %>: <strong><%= p.title %></strong></h5>
      </li>
      <% i += 1 %>
      <li class="list-group-item"><%= p.text.truncate(90) %></li>
      <li class="list-group-item d-flex flex-row" id="lks">
        <%= link_to 'View post', user_post_path(@user, p), class: 'btn btn-view' %>
        <p>Comments: <%= p.comments_counter %></p>
        <p>Likes: <%= p.likes_counter %></p>
      </li>
    <% end %>
  </ul>
  <div class="card-body d-flex flex-row" id="navigate">
  <%= link_to "Create new post", data: { turbo: false }, new_user_post_path(@user) %>
    <%= link_to 'View more posts', user_posts_path(@user), class: 'btn btn-lg' %>
    <%= link_to 'Back', users_path(@user), class: 'btn btn-lg btn-danger' %>
  </div>
</div>